import type { Ebook } from "./ebooks";

export const LIFE_EBOOKS: Ebook[] = [
  {
    id: "ebook-personal-finance-ng",
    slug: "personal-finance-nigeria",
    title: "Personal Finance Playbook (Nigeria)",
    subtitle: "Cash clarity, buffers, debt plans, and calm money habits",
    author: "DoyinTech",
    priceNgn: 8500,
    amountKobo: 850000,
    pagesLabel: "Full guide · 8 chapters",
    category: "Finance",
    coverFrom: "#0f172a",
    coverTo: "#0d9488",
    accent: "#2dd4bf",
    icon: "N",
    coverImage: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=900&q=85",
    badge: "Wealth",
    blurb: "A practical money system for workers and small business owners: see your cash, build buffers, handle debt, and grow without hype.",
    benefits: ["7-day expense truth exercise", "Simple pot system for income", "Debt attack order", "Monthly money date checklist"],
    chapters: [],
  },
  {
    id: "ebook-student-productivity",
    slug: "student-productivity-system",
    title: "Student Productivity System",
    subtitle: "Focus, active recall, and exam-week protocols that work",
    author: "DoyinTech",
    priceNgn: 6500,
    amountKobo: 650000,
    pagesLabel: "Full guide · 8 chapters",
    category: "Education",
    coverFrom: "#1e3a5f",
    coverTo: "#6366f1",
    accent: "#a5b4fc",
    icon: "Edu",
    coverImage: "https://images.unsplash.com/photo-14565130808-af05246b553?auto=format&fit=crop&w=900&q=85",
    badge: "Education",
    blurb: "Study as a performance skill: environment design, active recall, spaced practice, and a calm exam-week plan.",
    benefits: ["Phone-free deep study setup", "Active recall methods", "Semester planning backward from exams", "Exam week protocol"],
    chapters: [],
  },
  {
    id: "ebook-fitness-busy",
    slug: "fitness-for-busy-people",
    title: "Fitness for Busy People",
    subtitle: "Strength, walking, and food defaults that fit real schedules",
    author: "DoyinTech",
    priceNgn: 6900,
    amountKobo: 690000,
    pagesLabel: "Full guide · 8 chapters",
    category: "Fitness",
    coverFrom: "#14532d",
    coverTo: "#22c55e",
    accent: "#86efac",
    icon: "Fit",
    coverImage: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=85",
    badge: "Health",
    blurb: "Minimum effective fitness for founders and professionals: strength patterns, daily walking, food defaults, and a 28-day starter plan.",
    benefits: ["30-40 min strength templates", "Walking targets that stick", "Food defaults for energy", "28-day plan"],
    chapters: [],
  },
  {
    id: "ebook-home-food-budget",
    slug: "home-food-on-a-budget",
    title: "Home Food on a Budget",
    subtitle: "Menus, shopping discipline, and batch cooking that save money",
    author: "DoyinTech",
    priceNgn: 5900,
    amountKobo: 590000,
    pagesLabel: "Full guide · 8 chapters",
    category: "Food",
    coverFrom: "#7c2d12",
    coverTo: "#ea580c",
    accent: "#fdba74",
    icon: "Food",
    coverImage: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=900&q=85",
    badge: "Home",
    blurb: "Plan meals, shop with a list, batch cook, and stop delivery from quietly draining your budget.",
    benefits: ["Weekly menu framework", "Shopping list rules", "Batch cooking bases", "Delivery budget limits"],
    chapters: [],
  },
  {
    id: "ebook-culture-community",
    slug: "culture-and-community-advantage",
    title: "Culture and Community Advantage",
    subtitle: "Reputation, networks, and belonging as practical assets",
    author: "DoyinTech",
    priceNgn: 7200,
    amountKobo: 720000,
    pagesLabel: "Full guide · 8 chapters",
    category: "Culture",
    coverFrom: "#4a1d3f",
    coverTo: "#c026d3",
    accent: "#f0abfc",
    icon: "Cul",
    coverImage: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=85",
    badge: "Culture",
    blurb: "How culture, reputation, and community networks shape opportunity and how to build them deliberately.",
    benefits: ["Reputation habits", "Boundary scripts with family pressure", "Trust + written deals", "Contribution mindset"],
    chapters: [],
  },
  {
    id: "ebook-wealth-habits",
    slug: "wealth-habits",
    title: "Wealth Habits",
    subtitle: "Behaviours that compound income, assets, and options",
    author: "DoyinTech",
    priceNgn: 8900,
    amountKobo: 890000,
    pagesLabel: "Full guide · 8 chapters",
    category: "Wealth",
    coverFrom: "#1c1917",
    coverTo: "#b45309",
    accent: "#fbbf24",
    icon: "W",
    coverImage: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=900&q=85",
    badge: "Wealth",
    blurb: "Wealth as behaviour: save rates, skill growth, network quality, risk caps, and quarterly reviews.",
    benefits: ["Save and skill rates", "Lifestyle lag principle", "Risk management rules", "Quarterly wealth review"],
    chapters: [],
  },
  {
    id: "ebook-education-lifelong",
    slug: "lifelong-learning-system",
    title: "Lifelong Learning System",
    subtitle: "What to learn, how to practise, and how to prove skill",
    author: "DoyinTech",
    priceNgn: 7400,
    amountKobo: 740000,
    pagesLabel: "Full guide · 8 chapters",
    category: "Education",
    coverFrom: "#0c4a6e",
    coverTo: "#0284c7",
    accent: "#7dd3fc",
    icon: "Learn",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=85",
    badge: "Education",
    blurb: "A practical system for learning after school: choose skills the market pays for, practise deliberately, and show proof.",
    benefits: ["Skill selection filter", "Weekly learning blocks", "Portfolio proof", "Yearly learning plan"],
    chapters: [],
  },
];
