export type ColumnProfile = {
  name: string;
  kind: "numeric" | "categorical";
  missing: number;
  n: number;
  mean?: number;
  sd?: number;
  min?: number;
  max?: number;
  frequencies?: { value: string; count: number; pct: number }[];
};

export type AnalysisResult = {
  rowCount: number;
  columnCount: number;
  columns: ColumnProfile[];
  narrative: string;
  tablesMarkdown: string;
};

function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let cur = "";
  let inQuotes = false;
  const s = text.replace(/^\uFEFF/, "");
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (inQuotes) {
      if (c === '"') {
        if (s[i + 1] === '"') {
          cur += '"';
          i++;
        } else inQuotes = false;
      } else cur += c;
    } else if (c === '"') inQuotes = true;
    else if (c === ",") {
      row.push(cur.trim());
      cur = "";
    } else if (c === "\n" || c === "\r") {
      if (c === "\r" && s[i + 1] === "\n") i++;
      row.push(cur.trim());
      cur = "";
      if (row.some((x) => x !== "")) rows.push(row);
      row = [];
    } else cur += c;
  }
  if (cur.length || row.length) {
    row.push(cur.trim());
    if (row.some((x) => x !== "")) rows.push(row);
  }
  return rows;
}

function isNumericValue(v: string): boolean {
  if (!v) return false;
  return Number.isFinite(Number(String(v).replace(/,/g, "")));
}

function mean(nums: number[]): number {
  return nums.reduce((a, b) => a + b, 0) / nums.length;
}

function sd(nums: number[], m: number): number {
  if (nums.length < 2) return 0;
  const v = nums.reduce((a, b) => a + (b - m) ** 2, 0) / (nums.length - 1);
  return Math.sqrt(v);
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

export function analyzeQuestionnaireCsv(csvText: string): AnalysisResult {
  const grid = parseCsv(csvText);
  if (grid.length < 2) throw new Error("Need a header row and at least one data row.");
  const headers = grid[0].map((h, i) => h || `Column_${i + 1}`);
  const rows = grid.slice(1).filter((r) => r.some((c) => c !== "")).slice(0, 5000);

  const columns: ColumnProfile[] = headers.map((name, colIdx) => {
    const values = rows.map((r) => (r[colIdx] ?? "").trim());
    const nonEmpty = values.filter((v) => v !== "");
    const missing = values.length - nonEmpty.length;
    const numericRatio =
      nonEmpty.length === 0 ? 0 : nonEmpty.filter(isNumericValue).length / nonEmpty.length;
    const kind: "numeric" | "categorical" = numericRatio >= 0.8 ? "numeric" : "categorical";

    if (kind === "numeric") {
      const nums = nonEmpty.filter(isNumericValue).map((v) => Number(String(v).replace(/,/g, "")));
      const m = nums.length ? mean(nums) : 0;
      return {
        name,
        kind,
        missing,
        n: nums.length,
        mean: nums.length ? round2(m) : undefined,
        sd: nums.length ? round2(sd(nums, m)) : undefined,
        min: nums.length ? round2(Math.min(...nums)) : undefined,
        max: nums.length ? round2(Math.max(...nums)) : undefined,
      };
    }

    const counts = new Map<string, number>();
    for (const v of nonEmpty) counts.set(v, (counts.get(v) || 0) + 1);
    const frequencies = [...counts.entries()]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 12)
      .map(([value, count]) => ({
        value: value.slice(0, 80),
        count,
        pct: nonEmpty.length ? round2((count / nonEmpty.length) * 100) : 0,
      }));
    return { name, kind, missing, n: nonEmpty.length, frequencies };
  });

  const narrative = [
    `This section presents analysis of ${rows.length} questionnaire response(s) across ${columns.length} variable(s). Verify with your supervisor.`,
    "",
    "Sample overview",
    `A total of ${rows.length} valid rows were included after removing empty rows.`,
    "",
    "Summary",
    "Descriptive results summarise main patterns. Full statistical packages are available via the research project portal.",
    "",
    "- Draft generated by DoyinTech Student Analyzer.",
  ].join("\n");

  const tablesMarkdown = columns
    .map((c) => {
      if (c.kind === "numeric") {
        return `### ${c.name}\n| Stat | Value |\n| --- | --- |\n| N | ${c.n} |\n| Mean | ${c.mean ?? "-"} |\n| SD | ${c.sd ?? "-"} |\n`;
      }
      const rowsMd = (c.frequencies || [])
        .map((f) => `| ${f.value.replace(/\|/g, "/")} | ${f.count} | ${f.pct} |`)
        .join("\n");
      return `### ${c.name}\n| Response | Count | % |\n| --- | --- | --- |\n${rowsMd}\n`;
    })
    .join("\n");

  return {
    rowCount: rows.length,
    columnCount: headers.length,
    columns,
    narrative,
    tablesMarkdown,
  };
}
