/**
 * SME pitch deck generator + optional live URL snapshot (Microlink).
 */

function clean(s: string, max = 400): string {
  return String(s || "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, max);
}

function normalizeUrl(raw: string): string | null {
  const t = clean(raw, 500);
  if (!t) return null;
  try {
    const withProto = /^https?:\/\//i.test(t) ? t : `https://${t}`;
    const u = new URL(withProto);
    if (!["http:", "https:"].includes(u.protocol)) return null;
    return u.toString();
  } catch {
    return null;
  }
}

export type PitchInput = {
  projectName: string;
  description: string;
  url?: string;
  audience?: string;
  ask?: string;
};

export type PitchResult = {
  slides: { title: string; body: string }[];
  markdown: string;
  screenshotUrl: string | null;
  pageTitle: string | null;
  pageDescription: string | null;
  finalUrl: string | null;
};

export async function fetchUrlSnapshot(url: string): Promise<{
  screenshotUrl: string | null;
  pageTitle: string | null;
  pageDescription: string | null;
  finalUrl: string | null;
}> {
  const endpoint = new URL("https://api.microlink.io");
  endpoint.searchParams.set("url", url);
  endpoint.searchParams.set("screenshot", "true");
  endpoint.searchParams.set("meta", "true");
  // optional key improves quota
  const key = process.env.MICROLINK_API_KEY?.trim();
  if (key) endpoint.searchParams.set("apiKey", key);

  try {
    const res = await fetch(endpoint.toString(), {
      next: { revalidate: 0 },
      signal: AbortSignal.timeout(25000),
    });
    if (!res.ok) {
      return { screenshotUrl: null, pageTitle: null, pageDescription: null, finalUrl: url };
    }
    const json = (await res.json()) as {
      status?: string;
      data?: {
        title?: string;
        description?: string;
        url?: string;
        screenshot?: { url?: string };
      };
    };
    return {
      screenshotUrl: json.data?.screenshot?.url || null,
      pageTitle: json.data?.title || null,
      pageDescription: json.data?.description || null,
      finalUrl: json.data?.url || url,
    };
  } catch {
    return { screenshotUrl: null, pageTitle: null, pageDescription: null, finalUrl: url };
  }
}

export async function generatePitchDeck(input: PitchInput): Promise<PitchResult> {
  const name = clean(input.projectName, 100) || "Project";
  const description =
    clean(input.description, 600) ||
    "A practical product that solves a clear customer problem.";
  const audience = clean(input.audience || "busy decision-makers", 120);
  const ask =
    clean(input.ask || "a pilot engagement or seed commitment to ship the next milestone", 200);
  const url = input.url ? normalizeUrl(input.url) : null;

  let screenshotUrl: string | null = null;
  let pageTitle: string | null = null;
  let pageDescription: string | null = null;
  let finalUrl: string | null = null;

  if (url) {
    const snap = await fetchUrlSnapshot(url);
    screenshotUrl = snap.screenshotUrl;
    pageTitle = snap.pageTitle;
    pageDescription = snap.pageDescription;
    finalUrl = snap.finalUrl;
  }

  const slides = [
    {
      title: "Title",
      body: `${name}\n\n${description.slice(0, 160)}\n\nFor: ${audience}`,
    },
    {
      title: "Problem",
      body: `${audience} still waste time and money on slow, fragmented workflows.\n\nExisting options are either too generic or too expensive to adopt quickly.\n\n${name} focuses on one sharp pain and a measurable outcome.`,
    },
    {
      title: "Solution",
      body: `${name} delivers: ${description}\n\nSimple onboarding. Clear pricing. Results within the first engagement cycle.`,
    },
    {
      title: "Product snapshot",
      body: url
        ? `Live product: ${finalUrl || url}\n${pageTitle ? `Page title: ${pageTitle}\n` : ""}${pageDescription ? `Meta: ${pageDescription}\n` : ""}${screenshotUrl ? "\n[Screenshot attached below]" : "\n(Screenshot unavailable — page may block capture.)"}`
        : "Add a public product URL to attach a live screenshot to this slide.",
    },
    {
      title: "Why now",
      body: `Customers already search for faster digital workflows.\n\nTeams that productise delivery and follow-up win more of the same demand.\n\n${name} is positioned to capture that shift with a focused offer.`,
    },
    {
      title: "The ask",
      body: `We are looking for ${ask}.\n\nNext step: schedule a short demo, agree scope, and start with a clear milestone.`,
    },
  ];

  const markdown = [
    `# Pitch deck — ${name}`,
    ``,
    ...slides.flatMap((s, i) => [
      `## Slide ${i + 1}: ${s.title}`,
      s.body,
      ``,
    ]),
    url ? `**Product URL:** ${finalUrl || url}` : "",
    screenshotUrl ? `**Screenshot:** ${screenshotUrl}` : "",
    ``,
    `---`,
    `*Generated by DoyinTech AI Tools · SME Pitch*`,
  ]
    .filter(Boolean)
    .join("\n");

  return {
    slides,
    markdown,
    screenshotUrl,
    pageTitle,
    pageDescription,
    finalUrl,
  };
}
