"use client";

import { useRef } from "react";
import type { OpsWorkspace } from "@/lib/ops/types";
import { formatNgn } from "@/lib/ops/store";

function weekRange() {
  const now = new Date();
  const day = now.getDay() || 7;
  const start = new Date(now);
  start.setDate(now.getDate() - day + 1);
  const end = new Date(start);
  end.setDate(start.getDate() + 6);
  const fmt = (d: Date) => d.toISOString().slice(0, 10);
  return { start: fmt(start), end: fmt(end), label: `${fmt(start)} → ${fmt(end)}` };
}

export default function OpsWeeklyReport({ ws }: { ws: OpsWorkspace }) {
  const ref = useRef<HTMLDivElement>(null);
  const range = weekRange();

  const openDeals = ws.deals.filter((d) => d.stage !== "paid" && d.stage !== "lost");
  const pipeline = openDeals.reduce((s, d) => s + (d.valueNgn || 0), 0);
  const unpaid = ws.invoices.filter((i) => i.status === "sent" || i.status === "overdue");
  const unpaidSum = unpaid.reduce((s, i) => s + (i.amountNgn || 0), 0);
  const paidThis = ws.invoices.filter(
    (i) => i.status === "paid" && i.paidAt && i.paidAt.slice(0, 10) >= range.start
  );
  const paidSum = paidThis.reduce((s, i) => s + (i.amountNgn || 0), 0);
  const openTasks = (ws.tasks || []).filter((t) => !t.done);
  const overdueFollow = ws.deals.filter(
    (d) =>
      d.nextFollowUp &&
      d.nextFollowUp < range.start.slice(0, 10) &&
      d.stage !== "paid" &&
      d.stage !== "lost"
  );

  function printReport() {
    const node = ref.current;
    if (!node) return;
    const win = window.open("", "_blank", "noopener,noreferrer,width=900,height=700");
    if (!win) return;
    win.document.write(`<!DOCTYPE html><html><head><title>Weekly report — ${ws.orgName}</title>
<style>
  body { font-family: system-ui, sans-serif; color: #111; padding: 32px; max-width: 720px; margin: 0 auto; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .muted { color: #666; font-size: 13px; margin-bottom: 24px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 24px; }
  .card { border: 1px solid #e5e5e5; border-radius: 10px; padding: 14px; }
  .card strong { display: block; font-size: 20px; margin-top: 6px; }
  .card span { font-size: 11px; text-transform: uppercase; color: #888; letter-spacing: 0.04em; }
  h2 { font-size: 14px; margin: 20px 0 8px; }
  ul { margin: 0; padding-left: 18px; font-size: 13px; }
  li { margin-bottom: 4px; }
  footer { margin-top: 32px; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 12px; }
  @media print { body { padding: 12px; } }
</style></head><body>${node.innerHTML}
<footer>Generated by DoyinOps · doyintech.vercel.app/ops · ${new Date().toLocaleString()}</footer>
<script>window.onload=function(){window.print();}</script></body></html>`);
    win.document.close();
  }

  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5 shadow-[0_8px_32px_rgba(0,0,0,0.3)] backdrop-blur-xl">
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
        <div>
          <h3 className="text-sm font-semibold text-white">Weekly report</h3>
          <p className="text-[11px] text-white/40">{range.label}</p>
        </div>
        <button
          type="button"
          onClick={printReport}
          className="rounded-lg bg-[#ff8c14] px-4 py-2 text-xs font-semibold text-black"
        >
          Print / PDF
        </button>
      </div>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        {[
          ["Pipeline", formatNgn(pipeline)],
          ["Unpaid", formatNgn(unpaidSum)],
          ["Paid (week)", formatNgn(paidSum)],
          ["Open tasks", String(openTasks.length)],
        ].map(([l, v]) => (
          <div key={l} className="rounded-xl border border-white/[0.06] bg-[#0c1220]/80 p-3">
            <p className="text-[10px] uppercase tracking-wide text-white/40">{l}</p>
            <p className="mt-1 text-lg font-semibold text-white">{v}</p>
          </div>
        ))}
      </div>

      {/* Hidden print source */}
      <div className="hidden" ref={ref}>
        <h1>{ws.orgName} — Weekly ops report</h1>
        <p className="muted">Week of {range.label}</p>
        <div className="grid">
          <div className="card"><span>Open pipeline</span><strong>{formatNgn(pipeline)}</strong></div>
          <div className="card"><span>Unpaid invoices</span><strong>{formatNgn(unpaidSum)}</strong></div>
          <div className="card"><span>Paid this week</span><strong>{formatNgn(paidSum)}</strong></div>
          <div className="card"><span>Open tasks</span><strong>{openTasks.length}</strong></div>
        </div>
        <h2>Open deals ({openDeals.length})</h2>
        <ul>
          {openDeals.slice(0, 20).map((d) => (
            <li key={d.id}>
              {d.title} — {formatNgn(d.valueNgn)} ({d.stage})
              {d.nextFollowUp ? ` · follow-up ${d.nextFollowUp}` : ""}
            </li>
          ))}
          {openDeals.length === 0 && <li>None</li>}
        </ul>
        <h2>Unpaid invoices ({unpaid.length})</h2>
        <ul>
          {unpaid.slice(0, 20).map((i) => (
            <li key={i.id}>
              {i.number} — {formatNgn(i.amountNgn)} · due {i.dueDate} ({i.status})
            </li>
          ))}
          {unpaid.length === 0 && <li>None</li>}
        </ul>
        <h2>Overdue follow-ups ({overdueFollow.length})</h2>
        <ul>
          {overdueFollow.slice(0, 15).map((d) => (
            <li key={d.id}>
              {d.title} — was {d.nextFollowUp}
            </li>
          ))}
          {overdueFollow.length === 0 && <li>None</li>}
        </ul>
        <h2>Open tasks</h2>
        <ul>
          {openTasks.slice(0, 15).map((t) => (
            <li key={t.id}>
              {t.title}{t.dueDate ? ` · due ${t.dueDate}` : ""}
            </li>
          ))}
          {openTasks.length === 0 && <li>None</li>}
        </ul>
      </div>
    </div>
  );
}
