/** Central config — edit WhatsApp, email, Academy URL, brand here */
export const TOOLS_CONFIG = {
  brand: "DoyinTech",
  siteUrl: "https://doyintech.vercel.app",
  academyUrl: "https://doyintechacademy.vercel.app",
  email: "doyintechnology@outlook.com",
  whatsappNumber: "2348085343926",
  phoneDisplay: "+234 808 534 3926",
  currency: "NGN" as const,
  currencySymbol: "₦",
} as const;

export function whatsappUrl(message: string) {
  return `https://wa.me/${TOOLS_CONFIG.whatsappNumber}?text=${encodeURIComponent(message)}`;
}

export type ToolMeta = {
  slug: string;
  href: string;
  title: string;
  short: string;
  description: string;
  icon: string;
  category: "core" | "business" | "career" | "ai" | "utility";
};

export const TOOLS_META: ToolMeta[] = [
  {
    slug: "website-calculator",
    href: "/tools/website-calculator",
    title: "Website Price Calculator",
    short: "Estimate what your website project could cost.",
    description: "Interactive website development cost estimator for Nigerian businesses.",
    icon: "calculator",
    category: "core",
  },
  {
    slug: "business-audit",
    href: "/tools/business-audit",
    title: "Business Audit Tool",
    short: "Discover what's holding your business back online.",
    description: "Free online business digital audit.",
    icon: "audit",
    category: "core",
  },
  {
    slug: "security-scanner",
    href: "/tools/security-scanner",
    title: "Website Security Scanner",
    short: "Laser-scan a URL for bugs & risks, download PDF.",
    description:
      "Visual website vulnerability scan simulation with PDF report.",
    icon: "shield",
    category: "core",
  },
  {
    slug: "cv-builder",
    href: "/tools/cv-builder",
    title: "CV & Portfolio Builder",
    short: "Create a professional CV and portfolio.",
    description: "Free professional CV and portfolio generator.",
    icon: "cv",
    category: "core",
  },
  {
    slug: "digital-readiness",
    href: "/tools/digital-readiness",
    title: "Digital Readiness Checker",
    short: "Measure digital economy readiness.",
    description: "Assess digital transformation readiness.",
    icon: "readiness",
    category: "core",
  },
  {
    slug: "project-brief",
    href: "/tools/project-brief",
    title: "Project Brief Generator",
    short: "Turn your idea into a clear project brief.",
    description: "Structured project brief for websites, apps, and automation.",
    icon: "brief",
    category: "business",
  },
  {
    slug: "proposal-builder",
    href: "/tools/proposal-builder",
    title: "Proposal Builder",
    short: "Create a professional client proposal.",
    description: "Scope, timeline, investment, and deposit in a print-ready proposal.",
    icon: "proposal",
    category: "business",
  },
  {
    slug: "contract-generator",
    href: "/tools/contract-generator",
    title: "Contract Generator",
    short: "Generate a simple service agreement.",
    description: "Service agreement template with signature lines.",
    icon: "contract",
    category: "business",
  },
  {
    slug: "project-status",
    href: "/tools/project-status",
    title: "Project Status Page",
    short: "Share live project progress with clients.",
    description: "Discovery to Done status board clients can open anytime.",
    icon: "status",
    category: "business",
  },
  {
    slug: "tech-stack",
    href: "/tools/tech-stack",
    title: "Tech Stack Advisor",
    short: "Get a recommended stack for your product.",
    description: "Advice on Flutter, Laravel, Next.js, WordPress and more.",
    icon: "stack",
    category: "business",
  },
  {
    slug: "hosting-planner",
    href: "/tools/hosting-planner",
    title: "Hosting & Domain Planner",
    short: "Plan domain and hosting costs in Naira.",
    description: "Estimate domain and hosting needs for Nigerian projects.",
    icon: "hosting",
    category: "business",
  },
  {
    slug: "roi-calculator",
    href: "/tools/roi-calculator",
    title: "Website ROI Calculator",
    short: "Estimate return on a website investment.",
    description: "Simple ROI model for website and digital projects.",
    icon: "roi",
    category: "business",
  },
  {
    slug: "invoice-generator",
    href: "/tools/invoice-generator",
    title: "Invoice & Receipt Generator",
    short: "Create invoices, quotes, and paid receipts.",
    description: "Professional invoice and receipt PDF for freelancers and SMEs.",
    icon: "invoice",
    category: "business",
  },
  {
    slug: "whatsapp-checklist",
    href: "/tools/whatsapp-checklist",
    title: "WhatsApp Business Checklist",
    short: "Set up WhatsApp Business the right way.",
    description: "Practical checklist for Nigerian businesses on WhatsApp.",
    icon: "wa",
    category: "business",
  },
  {
    slug: "maintenance-picker",
    href: "/tools/maintenance-picker",
    title: "Maintenance Plan Picker",
    short: "Choose the right website care plan.",
    description: "Match your site to a maintenance package.",
    icon: "maintain",
    category: "business",
  },
  {
    slug: "email-signature",
    href: "/tools/email-signature",
    title: "Email Signature Generator",
    short: "Build a professional email signature.",
    description: "Clean HTML-ready email signature for business.",
    icon: "email",
    category: "business",
  },
  {
    slug: "salary-calculator",
    href: "/tools/salary-calculator",
    title: "Tech Salary & Rate Calculator",
    short: "Estimate Nigerian tech salaries and freelance rates.",
    description: "Planning ranges for junior to senior tech roles in Nigeria.",
    icon: "salary",
    category: "career",
  },
  {
    slug: "skill-gap",
    href: "/tools/skill-gap",
    title: "Skill Gap Checker",
    short: "See what to learn next for your tech path.",
    description: "Skill roadmap checker for backend, mobile, and AI tracks.",
    icon: "skills",
    category: "career",
  },
  {
    slug: "cover-letter",
    href: "/tools/cover-letter",
    title: "Cover Letter Generator",
    short: "Draft a professional cover letter.",
    description: "Structured cover letter builder for job applications.",
    icon: "letter",
    category: "career",
  },
  {
    slug: "project-ideas",
    href: "/tools/project-ideas",
    title: "Portfolio Project Ideas",
    short: "Get project ideas that impress employers.",
    description: "Portfolio project ideas for students and junior developers.",
    icon: "ideas",
    category: "career",
  },
  {
    slug: "interview-practice",
    href: "/tools/interview-practice",
    title: "Interview Practice",
    short: "Practice common tech interview questions.",
    description: "Role-based interview questions for developers.",
    icon: "interview",
    category: "career",
  },
  {
    slug: "ai-usecase",
    href: "/tools/ai-usecase",
    title: "AI Use-Case Finder",
    short: "Find AI automation ideas for your business.",
    description: "Discover practical AI and automation opportunities.",
    icon: "ai",
    category: "ai",
  },
  {
    slug: "chatbot-script",
    href: "/tools/chatbot-script",
    title: "Chatbot Script Generator",
    short: "Create FAQ scripts for WhatsApp or web chat.",
    description: "Generate starter chatbot and WhatsApp auto-reply scripts.",
    icon: "bot",
    category: "ai",
  },
  {
    slug: "qr-generator",
    href: "/tools/qr-generator",
    title: "QR Code Generator",
    short: "Create QR codes for links and WhatsApp.",
    description: "Free QR code generator for business links.",
    icon: "qr",
    category: "utility",
  },
  {
    slug: "password-generator",
    href: "/tools/password-generator",
    title: "Password Generator",
    short: "Generate strong random passwords.",
    description: "Secure password generator — runs in your browser.",
    icon: "lock",
    category: "utility",
  },
];

export const TOOL_CATEGORIES: {
  id: ToolMeta["category"];
  label: string;
}[] = [
  { id: "core", label: "Core tools" },
  { id: "business", label: "Business & growth" },
  { id: "career", label: "Career & learning" },
  { id: "ai", label: "AI & automation" },
  { id: "utility", label: "Quick utilities" },
];
